#//yaml 有分层，可以这么打
#yml和yaml是一个东西


spring:
  profiles:
    active: test,dev #选择激活application-test 和 application-dev 有重复的话引用的覆盖自带的
  jdbc:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql:///springboot_02
      username: root
      password: root


server:
  port: 80
#  ==server.port=80

#自己设置 也一样的


#集合
set:
  -a
  -b
  -c


database:
  host: localhost
  port: 5432
  username: admin
  password: password123

features:
  - 登录
  - 注册
  - 仪表盘